spring:
  profiles:
    include:
      - aws
        real-db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  devtools:
    livereload:
      enabled: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
