
spring:

#  config:
#    import: classpath:aws.yml

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true # h2 DB 초기데이터 추가하기위한 설정
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  #서버배포 시 서버에 상당한 부담이 되므로 false 적용할 것
  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

