spring:
  profiles:
    include:
      - aws
        real-db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
