
spring:
  h2:
    console:
      enabled: true

  datasource:
    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      jdbc-url: jdbc:h2:file:D:/june/ClimbLabs-api/testdb
      username: sa

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true